### ISSUE TITLE
Error spam in console and server lockup after loot_tables addition

### ISSUE THREAD

**Issue by leelawd** [GenDeathrow/Player-Skin-Mobs#5]
Here is the spamming error for clarification.
https://pastebin.com/NtcUpUVS

This is the solution to fix it, Simply add the "name" line with a name for the pool.
![image](https://user-images.githubusercontent.com/3026728/38452365-f2be14ea-3a3a-11e8-8cce-a6cc7ebcd6e7.png)

**Comment by GenDeathrow** [comment]
Thanks.. I really wasn't sure what to put in for a blank loot table. Strange I didn't get that error spamming.

**Comment by GenDeathrow** [comment]
v1.0.5
